FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    libsdl2-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY . /src

RUN mkdir -p build && cd build && \
    cmake ../src -DBUILD_LINUX_FRONTEND=ON && \
    make simcity-linux -j$(nproc)

FROM ubuntu:22.04
RUN apt-get update && apt-get install -y libsdl2-2.0-0 && rm -rf /var/lib/apt/lists/*
COPY --from=0 /build/frontend/linux/simcity-linux /app/
WORKDIR /app
CMD ["./simcity-linux"]
